/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#include "stm32f0xx.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{

	//uint8_t blink_values[32] = {1,0,1,0,1,0,0,1,1,1,0,1,1,1,0,1,1,1,0,0,1,0,1,0,1,0,0,0,0,0,0,0};
	uint32_t blink_sequence = 0b10101001110111011100101010000000;
	uint8_t i = 0;
	while(1) {
		// setup peripherals
		RCC->AHBENR |= RCC_AHBENR_GPIOAEN;
		GPIOA->MODER |= GPIO_MODER_MODER5_0;
//
//		for (i=0;i<32;i++) {
//			if(blink_values[i] == 1)
//				GPIOA->BSRR = (1<<5); // set
//			else
//				GPIOA->BRR = (1<<5);
//			for (volatile uint32_t i = 0; i < 100000; i++);
//
//		}
		while(blink_sequence) {
			if (blink_sequence & 1)
				GPIOA->BSRR = (1<<5); // set
			else
				GPIOA->BRR = (1<<5);
			for (volatile uint32_t i = 0; i < 100000; i++);
			blink_sequence >>= 1;
		}
//		GPIOA->ODR ^= (1<<5); // toggle
//		// wait
//		for (volatile uint32_t i = 0; i < 100000; i++);
	}

}
